runtime: custom  # Replace with the latest supported runtime for Flexible Environment
env: flex
entrypoint: gunicorn -b :$PORT main:app  # Replace with your actual app entry point

# Configure resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

liveness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1
